[package]
name = "SPE"
version = "0.0.1"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
vulkano = "*"
vulkano-shaders = "0.34.0"
winit = { version = "*", features = ["default", "rwh_05"] }
glam = "*"